name: Tests
on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'
      - name: Install dependencies
        run: go mod download
      - name: Build
        run: go build -v ./...
      - name: Run go vet
        run: go vet ./...
      - name: Test with the Go CLI
        run: go test ./...